### ISSUE TITLE
Project Stations

### ISSUE THREAD

**Issue by LastCrusader105** [Oasis-SS13/Oasis-SS13#401]
The below is concept art for a station idea I had and Ruko helped me build on
![E65FE62D-C813-4A10-803C-97F92F4FBC98](https://user-images.githubusercontent.com/56616002/101528594-6e5eb200-3987-11eb-9b0d-6ad057c0b3bf.jpeg)

Basic concept is the departments will be separated and cargo will be in middle

Q: how will we get atmos and power
A:power and atmos will be handled by each “station” via a mini atmos area
Thus giving atmos and engineering a more prominent job

Q:how will cargo be delivered
A:via mass drivers

Q:how will a medical antag get about to kill a scientist
A:either though a shuttle system or mass driver

Command and services will be together where all “stations” can go to

**Comment by ro5490** [comment]
Looks similar to a station /VG/ had a at one point

**Comment by ro5490** [comment]
![image](https://user-images.githubusercontent.com/17776299/101963320-56489600-3c06-11eb-99e9-7fb08dbdb9b8.png)

**Comment by ro5490** [comment]
https://github.com/vgstation-coders/vgstation13/pull/20234

**Comment by LastCrusader105** [comment]
yes thats the general concept
